name: Periodic health check

on:
  schedule:
    - cron:  '0 0 */3 * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://nameless-woodland-24434.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: false